#!/bin/sh
#
# lgrunnerd      Startup script for lgrunnerd
#
# chkconfig: - 87 12
# description: lgrunnerd is a Python-based daemon for processing luigi tasks from a job system
# config: /etc/lgrunner.d/lgrunnerd.conf
# pidfile: /var/run/user/{user_id}/lgrunnerd/lgrunnerd.pid
#
### BEGIN INIT INFO
# Provides: lgrunnerd
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Short-Description: start and stop lgrunner daemon
# Description: lgrunnerd is a Python-based daemon for processing luigi tasks from a job system
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/lgrunnerd ]; then
        . /etc/sysconfig/lgrunnerd
fi

lgrunnerd=/usr/local/bin/lgrunnerd.py
prog=lgrunnerd
pidfile=${PIDFILE-/var/run/lgrunnerd/lgrunnerd.pid}
logfile=${LOGFILE-/var/log/lgrunnerd/lgrunnerd.log}
RETVAL=0

OPTIONS=""

start() {
        echo -n $"Starting $prog: "

        if [[ -f ${pidfile} ]] ; then
            pid=$( cat $pidfile  )
            isrunning=$( ps -elf | grep  $pid | grep $prog | grep -v grep )

            if [[ -n ${isrunning} ]] ; then
                echo $"$prog already running"
                return 0
            fi
        fi
        python3 $lgrunnerd $OPTIONS
        RETVAL=$?
        [ $RETVAL = 0 ] && success || failure
        echo
        return $RETVAL
}

stop() {
    if [[ -f ${pidfile} ]] ; then
        pid=$( cat $pidfile )
        isrunning=$( ps -elf | grep $pid | grep $prog | grep -v grep | awk '{print $4}' )

        if [[ ${isrunning} -eq ${pid} ]] ; then
            echo -n $"Stopping $prog: "
            kill $pid
        else
            echo -n $"Stopping $prog: "
            success
        fi
        RETVAL=$?
        [ $RETVAL = 0 ] && success || failure
    fi
    echo
    return $RETVAL
}

reload() {
    echo -n $"Reloading $prog: "
    echo
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p $pidfile $lgrunnerd
    RETVAL=$?
    ;;
  restart)
    stop
    sleep 0.1
    start
    ;;
  force-reload|reload)
    reload
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|force-reload|reload|status}"
    RETVAL=2
esac

exit $RETVAL
